<?xml version="1.0" encoding="UTF-8"?>
<testsuite name="org.springframework.cache.interceptor.CacheErrorHandlerTests" tests="9" skipped="0" failures="0" errors="0" timestamp="2020-11-25T14:38:32" hostname="lichangbaodeMacBook-Pro.local" time="0.068">
  <properties/>
  <testcase name="clearFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.025"/>
  <testcase name="evictFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.005"/>
  <testcase name="getFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.006"/>
  <testcase name="putFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.005"/>
  <testcase name="getFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.005"/>
  <testcase name="getAndPutFail" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.006"/>
  <testcase name="putFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.006"/>
  <testcase name="evictFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.005"/>
  <testcase name="clearFailProperException" classname="org.springframework.cache.interceptor.CacheErrorHandlerTests" time="0.005"/>
  <system-out><![CDATA[]]></system-out>
  <system-err><![CDATA[]]></system-err>
</testsuite>
